### ISSUE TITLE
Failed job `fatal: unsafe repository ('/__w/T-Regx/T-Regx' is owned by someone else)`

### ISSUE THREAD

**Issue by Danon** [paambaati/codeclimate-action#536]
**Describe the bug**

Action fails with a vanilla configuration, my configuration looks like this, I think it's pretty standard.

```yaml
- name: Upload coverage results to Code Climate
  if: "${{ matrix.coverage != 'none' }}"
  uses: paambaati/codeclimate-action@v3.0.0
  continue-on-error: true
  env:
    CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
```

**Version of `codeclimate-action` you're using**
`v3.0.0`

**Example links**
1. Example build run with `debug: true`: https://github.com/T-Regx/T-Regx/runs/6261918186?check_suite_focus=true
2. Workflow config: https://github.com/T-Regx/T-Regx/blob/master/.github/workflows/build.yaml

**Expected behavior**

The action uploads coverage to code climate.

**Comment by paambaati** [comment]
@Danon This is a known issue with container-based actions – see https://github.com/actions/checkout/issues/760 – and it looks like this has been fixed. Try updating https://github.com/T-Regx/T-Regx/blob/946c9dd6c0ef493aee3677d5e3037063a7ee6840/.github/workflows/build.yaml?rgh-link-date=2022-05-02T18%3A06%3A37Z#L45 to this –

```diff
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
```

**Comment by Danon** [comment]
@paambaati I used `actions/checkout@v3` and get the same error: https://github.com/T-Regx/T-Regx/runs/6271561769?check_suite_focus=true

**Comment by Danon** [comment]
Also from what I read, the fix has been introduced: https://github.com/actions/checkout/issues/760#issuecomment-1099219280
but if `git` is used outside of the checkout action, it may still be an error, and I presume `codeclimate-action` does use `git`.

**Comment by paambaati** [comment]
@Danon Interesting; this package doesn't use `git` though.

**Comment by Danon** [comment]
@paambaati That's interesting.

I updated checkout to `v3` as well as `2.4.1` and the job still fails. What else can I try?
